apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-rbac
  namespace: argocd
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/component: rbac
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/compare-options: ServerSideDiff=true
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  source:
    repoURL: https://github.com/eitatech/deployments.git
    path: vault/argocd/vault/resources
    targetRevision: main
    directory:
      include: "rbac.yaml"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
  dependencies:
    - vault-app-dev
