apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-rbac
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  source:
    repoURL: https://github.com/eitatech/deployments.git
    path: argocd/apps/vault/resources
    targetRevision: main
    directory:
      include: "rbac.yaml"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  dependencies:
    - vault-app-dev
