apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # Nome específico para o ambiente
  name: vault-app
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/component: vault-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/compare-options: ServerSideDiff=true
    argocd.argoproj.io/sync-options: Prune=false
spec:
  project: default
  
  # Health check personalizado para Vault
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/image
        - /spec/replicas
  
  # Informações do projeto
  info:
    - name: Description
      value: "HashiCorp Vault deployment for secrets management"
    - name: Environment
      value: "Development"
  destination:
    server: https://kubernetes.default.svc
    # Namespace específico para o ambiente, para isolamento
    namespace: vault
  
  # A fonte é o chart Helm remoto da HashiCorp
  source:
    repoURL: https://github.com/eitatech/deployments.git
    path: vault/argocd/vault
    targetRevision: main
    
    # Configuração do Helm
    helm:
      # O nome do release no Kubernetes
      releaseName: vault
      
      # Chart remoto da HashiCorp
      chart: https://helm.releases.hashicorp.com/vault-0.30.0.tgz
      
      # Values files externos para melhor organização
      valueFiles:
        - values/base.yaml
        - values/dev.yaml

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m