apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: besu-rpc-route
  namespace: paladin
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`rpc-besu.cluster.eita.cloud`)
      kind: Rule
      services:
        - name: besu-rpc-lb
          kind: TraefikService
      middlewares:
        - name: besu-retry-middleware
  tls:
    secretName: rpc-besu-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: besu-ws-route
  namespace: paladin
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`ws-besu.cluster.eita.cloud`)
      kind: Rule
      services:
        - name: besu-ws-lb
          kind: TraefikService
      middlewares:
        - name: besu-ws-middleware
        - name: besu-retry-middleware
  tls:
    secretName: ws-besu-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: besu-graphql-route
  namespace: paladin
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`graphql-besu.cluster.eita.cloud`)
      kind: Rule
      services:
        - name: besu-graphql-lb
          kind: TraefikService
      middlewares:
        - name: besu-retry-middleware
  tls:
    secretName: graphql-besu-tls
