apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: graphql-besu-cert
  namespace: paladin
spec:
  secretName: graphql-besu-tls
  issuerRef:
    name: letsencrypt-certmanager
    kind: ClusterIssuer
  commonName: graphql-besu.cluster.eita.cloud
  dnsNames:
    - graphql-besu.cluster.eita.cloud
