apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: besu-rpc-lb
  namespace: blockchain
spec:
  weighted:
    services:
      - name: besu-node1-rpc
        port: 8545
        weight: 1
      - name: besu-node2-rpc
        port: 8545
        weight: 1
      - name: besu-node3-rpc
        port: 8545
        weight: 1
---
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: besu-ws-lb
  namespace: blockchain
spec:
  weighted:
    services:
      - name: besu-node1-ws
        port: 8546
        weight: 1
      - name: besu-node2-ws
        port: 8546
        weight: 1
      - name: besu-node3-ws
        port: 8546
        weight: 1
---
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: besu-graphql-lb
  namespace: blockchain
spec:
  weighted:
    services:
      - name: besu-node1-graphql
        port: 8547
        weight: 1
      - name: besu-node2-graphql
        port: 8547
        weight: 1
      - name: besu-node3-graphql
        port: 8547
        weight: 1
