apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: besu-ws-middleware
  namespace: blockchain
spec:
  headers:
    customRequestHeaders:
      Connection: "Upgrade"
      Upgrade: "websocket"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: besu-retry-middleware
  namespace: blockchain
spec:
  retry:
    attempts: 3
    initialInterval: "500ms"
