{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault-ingress
  namespace: vault
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-certmanager"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - vault.{{ .Values.domain }}
    secretName: vault-tls
  rules:
  - host: vault.{{ .Values.domain }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.serviceName }}
              port:
                number: {{ .Values.servicePort }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vault-ui-ingress
  namespace: vault
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`vault.{{ .Values.domain }}`)
      kind: Rule
      services:
        - name: {{ .Values.serviceName }}
          port: {{ .Values.servicePort }}
  tls:
    secretName: vault-tls
{{- end }}
