apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paladin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/italo-moraes/bacen-drex-kubernetes-dev-stack.git'
    path: paladin/argocd/paladin
    helm:
      valueFiles:
        - environments/values.yaml
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: paladin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
