# Valores base que se aplicam a todos os ambientes (dev, stg, prod)
# a menos que sejam sobrescritos.

# Configurações globais do chart
global:
  # Por padrão, TLS deve estar habilitado. O ambiente de dev irá desabilitá-lo.
  tlsDisable: false

# O injetor de sidecar é útil em todos os ambientes.
injector:
  enabled: true

server:
  # Desabilitar o modo 'dev' do Vault é crucial para a persistência de dados.
  dev:
    enabled: false

  # Configuração de armazenamento de dados. O tamanho pode ser sobrescrito.
  dataStorage:
    size: 5Gi
    # storageClass será null por padrão, permitindo que o provisionador padrão do cluster atue.

  # Configurações de log são geralmente consistentes.
  logLevel: "info"
  logFormat: "standard"

  # As probes de prontidão são importantes para a estabilidade em todos os ambientes.
  readinessProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 15
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 3

  # Recursos base. Cada ambiente pode (e deve) sobrescrever isso.
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

  # O serviço da UI estará habilitado, mas o tipo será definido por ambiente.
  ui:
    enabled: true
    serviceType: "ClusterIP" # Padrão seguro. Dev irá sobrescrever para NodePort.

  # O serviço principal do Vault.
  service:
    enabled: true
    type: ClusterIP # Padrão seguro.