apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefly-core
  namespace: firefly-gateway
  labels:
    app: firefly-core
    component: core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firefly-core
      component: core
  template:
    metadata:
      labels:
        app: firefly-core
        component: core
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
      - name: firefly
        image: ghcr.io/italoag/firefly:latest-arm64
        imagePullPolicy: Always
        command: ["firefly"]
        args: ["-f", "/etc/firefly/firefly.core.yaml"]
        ports:
        - containerPort: 5000
          name: http
        - containerPort: 5001
          name: admin
        - containerPort: 6000
          name: metrics
        env:
        - name: FIREFLY_DEBUG
          value: "true"
        volumeMounts:
        - name: config
          mountPath: /etc/firefly
          readOnly: true
        livenessProbe:
          httpGet:
            path: /api/v1/status
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/status
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: config
        configMap:
          name: firefly-config
---
apiVersion: v1
kind: Service
metadata:
  name: firefly-core
  namespace: firefly-gateway
  labels:
    app: firefly-core
    component: core
spec:
  selector:
    app: firefly-core
    component: core
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  - name: admin
    port: 5001
    targetPort: 5001
  - name: metrics
    port: 6000
    targetPort: 6000
  type: ClusterIP