apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefly-evmconnect
  namespace: firefly-gateway
  labels:
    app: firefly-evmconnect
    component: evmconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firefly-evmconnect
      component: evmconnect
  template:
    metadata:
      labels:
        app: firefly-evmconnect
        component: evmconnect
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
      - name: evmconnect
        image: ghcr.io/hyperledger/firefly-evmconnect:v1.3.20
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: EVMCONNECT_BACKEND_CHAINID
          value: "1337"
        - name: EVMCONNECT_BACKEND_URL
          value: "http://firefly-signer.firefly-gateway.svc:8545"
        - name: EVMCONNECT_POLICYENGINE_SIMPLE_FIXEDGASPRICE
          value: "0"
        - name: EVMCONNECT_POLICYENGINE_SIMPLE_GASORACLE_MODE
          value: "fixed"
        - name: EVMCONNECT_LOG_LEVEL
          value: "debug"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /api/v1/status
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/status
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: firefly-evmconnect
  namespace: firefly-gateway
  labels:
    app: firefly-evmconnect
    component: evmconnect
spec:
  selector:
    app: firefly-evmconnect
    component: evmconnect
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  type: ClusterIP