apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefly-tokens-erc1155
  namespace: firefly-gateway
  labels:
    app: firefly-tokens-erc1155
    component: tokens-erc1155
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firefly-tokens-erc1155
      component: tokens-erc1155
  template:
    metadata:
      labels:
        app: firefly-tokens-erc1155
        component: tokens-erc1155
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
      - name: tokens
        image: ghcr.io/hyperledger/firefly-tokens-erc1155:v1.3.4
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: TOKENS_CONNECTOR_URL
          value: "http://firefly-evmconnect:5000"
        - name: TOKENS_LOG_LEVEL
          value: "debug"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /api/v1/status
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/status
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: firefly-tokens-erc1155
  namespace: firefly-gateway
  labels:
    app: firefly-tokens-erc1155
    component: tokens-erc1155
spec:
  selector:
    app: firefly-tokens-erc1155
    component: tokens-erc1155
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefly-tokens-erc20erc721
  namespace: firefly-gateway
  labels:
    app: firefly-tokens-erc20erc721
    component: tokens-erc20erc721
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firefly-tokens-erc20erc721
      component: tokens-erc20erc721
  template:
    metadata:
      labels:
        app: firefly-tokens-erc20erc721
        component: tokens-erc20erc721
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
      - name: tokens
        image: ghcr.io/hyperledger/firefly-tokens-erc20-erc721:v1.3.4
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: TOKENS_CONNECTOR_URL
          value: "http://firefly-evmconnect:5000"
        - name: TOKENS_LOG_LEVEL
          value: "debug"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /api/v1/status
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/status
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: firefly-tokens-erc20erc721
  namespace: firefly-gateway
  labels:
    app: firefly-tokens-erc20erc721
    component: tokens-erc20erc721
spec:
  selector:
    app: firefly-tokens-erc20erc721
    component: tokens-erc20erc721
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  type: ClusterIP