apiVersion: v1
items:
- apiVersion: traefik.io/v1alpha1
  kind: TraefikService
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"traefik.io/v1alpha1","kind":"TraefikService","metadata":{"annotations":{},"name":"besu-graphql-lb","namespace":"paladin"},"spec":{"weighted":{"services":[{"name":"besu-node1-graphql","port":8547,"weight":1},{"name":"besu-node2-graphql","port":8547,"weight":1},{"name":"besu-node3-graphql","port":8547,"weight":1}]}}}
    creationTimestamp: "2025-05-05T17:41:48Z"
    generation: 1
    name: besu-graphql-lb
    namespace: paladin
    resourceVersion: "9849863"
    uid: 16ea83c9-b2ad-4539-8fb5-a26bb60a2a65
  spec:
    weighted:
      services:
      - name: besu-node1-graphql
        port: 8547
        weight: 1
      - name: besu-node2-graphql
        port: 8547
        weight: 1
      - name: besu-node3-graphql
        port: 8547
        weight: 1
- apiVersion: traefik.io/v1alpha1
  kind: TraefikService
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"traefik.io/v1alpha1","kind":"TraefikService","metadata":{"annotations":{},"name":"besu-rpc-lb","namespace":"paladin"},"spec":{"weighted":{"services":[{"name":"besu-node1-rpc","port":8545,"weight":1},{"name":"besu-node2-rpc","port":8545,"weight":1},{"name":"besu-node3-rpc","port":8545,"weight":1}]}}}
    creationTimestamp: "2025-05-05T17:41:48Z"
    generation: 1
    name: besu-rpc-lb
    namespace: paladin
    resourceVersion: "9849860"
    uid: a160af7d-0d83-4600-aa0b-702663a9c048
  spec:
    weighted:
      services:
      - name: besu-node1-rpc
        port: 8545
        weight: 1
      - name: besu-node2-rpc
        port: 8545
        weight: 1
      - name: besu-node3-rpc
        port: 8545
        weight: 1
- apiVersion: traefik.io/v1alpha1
  kind: TraefikService
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"traefik.io/v1alpha1","kind":"TraefikService","metadata":{"annotations":{},"name":"besu-ws-lb","namespace":"paladin"},"spec":{"weighted":{"services":[{"name":"besu-node1-ws","port":8546,"weight":1},{"name":"besu-node2-ws","port":8546,"weight":1},{"name":"besu-node3-ws","port":8546,"weight":1}]}}}
    creationTimestamp: "2025-05-05T17:41:48Z"
    generation: 1
    name: besu-ws-lb
    namespace: paladin
    resourceVersion: "9849862"
    uid: bd03ce63-711e-421f-9827-a29c30104eb6
  spec:
    weighted:
      services:
      - name: besu-node1-ws
        port: 8546
        weight: 1
      - name: besu-node2-ws
        port: 8546
        weight: 1
      - name: besu-node3-ws
        port: 8546
        weight: 1
kind: List
metadata:
  resourceVersion: ""
