###############################################################################
# mongodb-values.yaml  –  Bitnami MongoDB 16.5.23 (stand-alone)               #
###############################################################################

# --------------------------------------------------------------------------- #
# 1)  Arquitetura                                                             #
# --------------------------------------------------------------------------- #
# image:
#   registry: docker.io
#   repository: mongodb/mongodb-community-server
#   tag: 8.0.8-ubi8
architecture: standalone            # um único Pod (sem ReplicaSet/Sharding)

# --------------------------------------------------------------------------- #
# 2)  Autenticação                                                           #
# --------------------------------------------------------------------------- #
auth:
  enabled: true
  rootUser: root                    # padrão; pode omitir
  rootPassword: ""                  # deixar vazio → passado via --set no script
  database: admin                   # DB onde o root autentica

# --------------------------------------------------------------------------- #
# 3)  Persistência                                                           #
# --------------------------------------------------------------------------- #
primary:
  persistence:
    enabled: true
    size: 8Gi                       # PVC de 8 GiB
    storageClass: ""                # “” → usar storageClass default do cluster

# --------------------------------------------------------------------------- #
# 4)  Service interno                                                        #
# --------------------------------------------------------------------------- #
service:
  type: ClusterIP                   # nenhum NodePort/LB; hostNetwork cuida
  port: 27017

# --------------------------------------------------------------------------- #
# 5)  Recursos                                                               #
# --------------------------------------------------------------------------- #
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

# --------------------------------------------------------------------------- #
# 6)  Probes (mantidos padrão)                                               #
# --------------------------------------------------------------------------- #
livenessProbe:
  enabled: true
readinessProbe:
  enabled: true
