apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefly-sandbox
  namespace: firefly
  labels:
    app.kubernetes.io/name: firefly
    app.kubernetes.io/instance: firefly
    app.kubernetes.io/component: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: firefly
      app.kubernetes.io/instance: firefly
      app.kubernetes.io/component: sandbox
  template:
    metadata:
      labels:
        app.kubernetes.io/name: firefly
        app.kubernetes.io/instance: firefly
        app.kubernetes.io/component: sandbox
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      initContainers:
        - name: wait-for-firefly
          image: busybox:1.36.1
          command: ['sh', '-c', 'until wget -q --spider http://firefly:5000/api/v1/status; do echo waiting for firefly; sleep 5; done; echo firefly is ready']
      containers:
        - name: firefly-sandbox
          image: ghcr.io/italoag/firefly-sandbox:latest-arm64
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          env:
            - name: SERVER_PORT
              value: "3001"
            - name: FF_ENDPOINT
              value: "http://firefly:5000"
            - name: FF_DEFAULT_NAMESPACE
              value: "default"
            - name: NODE_ENV
              value: "development"
            - name: DEBUG
              value: "*"
            - name: LOG_LEVEL
              value: "debug"
            - name: FIREFLY_LOG_LEVEL
              value: "debug"
            - name: UI_PATH
              value: "/app/ui/build"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: firefly-sandbox
  namespace: firefly
  labels:
    app.kubernetes.io/name: firefly
    app.kubernetes.io/instance: firefly
    app.kubernetes.io/component: sandbox
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: firefly
    app.kubernetes.io/instance: firefly
    app.kubernetes.io/component: sandbox
