apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: firefly-cors
  namespace: firefly
spec:
  headers:
    accessControlAllowOriginList:
      - "*"
    accessControlAllowHeaders:
      - "*"
    accessControlAllowMethods:
      - "*"