apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/italo-goncalves/bacen-drex-kubernetes-dev-stack'
    path: kafka/argocd/kafka
    targetRevision: HEAD
    helm:
      valueFiles:
        - environments/values-dev.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kafka-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
