###############################################################################
# Bitnami PostgreSQL chart – values.yaml                                      #
#                                                                             #
# Observação 📌                                                               #
# • A senha do super-user **NÃO** fica aqui;                                  #  
#   o script `deploy-postgresql.sh` injeta via                                #
#     --set auth.postgresPassword=$POSTGRES_PASSWORD                          #
# • hostNetwork e dnsPolicy também são aplicados pelo script, não pelo chart  #
###############################################################################

# --------------------------------------------------------------------------- #
# 1)  Arquitetura                                                             #
# --------------------------------------------------------------------------- #
architecture: standalone            # um único Pod (sem réplica)

# --------------------------------------------------------------------------- #
# 2)  Autenticação                                                            #
# --------------------------------------------------------------------------- #
auth:
  enablePostgresUser: true          # cria o usuário “postgres” (default true)
  postgresPassword: ""              # será passado pelo script via --set
  database: postgres                # DB inicial (padrão “postgres”)

# --------------------------------------------------------------------------- #
# 3)  Persistência                                                            #
# --------------------------------------------------------------------------- #
primary:
  persistence:
    enabled: true
    size: 8Gi                        # PVC de 8 GiB
    storageClass: ""                 # “” → usa StorageClass padrão do cluster

# --------------------------------------------------------------------------- #
# 4)  Service interno                                                         #
# --------------------------------------------------------------------------- #
service:
  type: ClusterIP                    # nenhuma exposição extra; hostNetwork fará isso
  port: 5432

# --------------------------------------------------------------------------- #
# 5)  Recursos                                                                #
# --------------------------------------------------------------------------- #
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

# --------------------------------------------------------------------------- #
# 6)  Probes (mantidos padrão)                                                #
# --------------------------------------------------------------------------- #
livenessProbe:
  enabled: true
readinessProbe:
  enabled: true
