apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: firefly-signer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hyperledger/firefly-helm-charts.git # Ou o seu repositório do chart
    targetRevision: main
    path: charts/firefly-signer # Caminho para o chart do firefly-signer
    helm:
      values: |
        image:
          repository: ghcr.io/italoag/firefly-signer
          pullPolicy: Always
          tag: "latest"

        backend:
          url: "http://besu-node1-rpc.paladin.svc:8545"
          chainId: 1337

        signer:
          enabled: true

        service:
          type: ClusterIP
          port: 8545

        resources: {}

        podSecurityContext:
          fsGroup: 1001

        securityContext: {}

        podAnnotations: {}

        nodeSelector:
          kubernetes.io/arch: arm64
        tolerations: []
        affinity: {}

        persistentVolume:
          enabled: false
          size: 1Gi
          storageClass: ""
          accessModes:
            - ReadWriteOnce

        extraEnv: []
        initContainers: ""
        extraContainers: ""

        metrics:
          enabled: true
          serviceMonitor:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: firefly # Namespace onde o Firefly Signer será implantado
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
